server:
    port: 8080

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
              defaultZone: http://malvarez.cern.ch/game-of-life/eureka/
        healthcheck:
            enabled: true
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: false
        eviction-interval-timer-in-ms: 10000

---

spring:
    profiles: local

server:
    contextPath: /game-of-life

eureka:
    client:
        serviceUrl:
              defaultZone: http://localhost:8080/eureka/
