server:
    port: 8080

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
              defaultZone: http://malvarez.cern.ch/game-of-life/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0

---

spring:
    profiles: local

eureka:
    client:
        serviceUrl:
              defaultZone: http://localhost:8080/eureka/
